name: deploy

on: push

jobs:
  test-then-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          tar -xzf node_modules_backup/node_modules.tar.gz;

          # Only reinstall if tests fail
          npm test || npm install
          
      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Archive node_modules
        run: source scripts/archive_node_modules_if_needed.sh
