name: deploy

on: push

jobs:
  test-then-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Deploy
        run: npm run deploy
