name: deploy

on: push

jobs:
  test-then-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm run smart-install

          # If tests fail, try reinstalling
          npm test || npm install

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Archive node_modules
        run: |
          (cmp package.json node_modules_backup/package_json_checksum.json || npm run archive-node-modules) &&

          git config --global user.name 'GitHub Actions Bot' &&
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com' &&
          git status &&
          git add node_modules_backup &&

          # The commit operation is permitted to fail because it's possible
          # that no changes were made to `node_modules` (since you can edit `package.json`
          # without installing, or modifying the `dependencies` at all, for that matter).
          (git commit -am "Backup node_modules" || echo "Current backup is up to date.") &&

          # Since we're not using a PAT, we can safely push without
          # (recursively) triggering the deploy job.
          git push
