name: deploy

on: push

jobs:
  test-then-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          tar -xzf node_modules_backup/node_modules.tar.gz;
          
          # Only reinstall if tests fail
          npm test || npm install
          
      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Archive node_modules
        run: |
          rm node_modules_backup/node_modules.tar.gz; tar -czf node_modules_backup/node_modules.tar.gz node_modules/ &&
          git config --global user.name 'GitHub Actions Bot' &&
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com' &&
          git add . &&

          # The commit operation is permitted to fail because it's possible
          # that no changes were made to `node_modules`.
          (git commit -am "Backup node_modules"; true) &&

          # Since we're not using a PAT, we can safely push without
          # (recursively) triggering the deploy job.
          git push
