name: deploy

on: push

jobs:
  test-then-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test

      # We need to set up the Git username and email
      # so the `gh-pages` tool will know how to write
      # its commit.
      - name: Set Git username and email
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" &&
          git config --global user.name "GitHub Actions Bot"

      - name: Deploy
        run: npm run deploy
